url: "https://hodgesiv.com"
timezone: America/New_York

development:
  bind: "ssl://0.0.0.0:4000"

permalink: simple
content_engine: resource
template_engine: serbea

collections:
  now_entries:
    output: true
    sort_direction: descending
  newsletters:
    output: false # we'll just reference them from an archive page, but the actual issues are legacy static files
    sort_direction: descending
  podcast:
    output: true
    sort_direction: descending
  projects:
    output: false
    sort_by: order
    sort_direction: ascending
  broadcasts:
    output: true
    sort_direction: descending

pagination:
  enabled: true
  title: ":title (pg. :num)"
  per_page: 15
